#ifndef SS_SOLAR_SYSTEM_CONSTANTS_H
#define SS_SOLAR_SYSTEM_CONSTANTS_H


#define EARTH_MASS			5.98E24f			// kg
#define EARTH_RADIUS		6380000.0f		// m
#define ASTRONOMIC_UNIT		149597892000.0f	// m
#define SEC_PER_YEAR		31556926.0f		// sec/yr

// Rayon des planetes (m)
#define SOLEIL_RAYON	109.0f*EARTH_RADIUS
#define MERCURE_RAYON	0.387f*EARTH_RADIUS
#define VENUS_RAYON		0.95f*EARTH_RADIUS
#define TERRE_RAYON		1.0f*EARTH_RADIUS
#define MARS_RAYON		0.53f*EARTH_RADIUS
#define JUPITER_RAYON	11.2f*EARTH_RADIUS
#define SATURNE_RAYON	9.3f*EARTH_RADIUS
#define URANUS_RAYON	4.0f*EARTH_RADIUS
#define NEPTUNE_RAYON 	3.9f*EARTH_RADIUS
#define PLUTON_RAYON	0.18f*EARTH_RADIUS

// Orbit radius	(demi grand-axe...) (m) 
#define MERCURE_ORBIT_A	0.387f*ASTRONOMIC_UNIT
#define VENUS_ORBIT_A	0.723f*ASTRONOMIC_UNIT
#define TERRE_ORBIT_A	1.0f*ASTRONOMIC_UNIT
#define MARS_ORBIT_A	1.524f*ASTRONOMIC_UNIT
#define JUPITER_ORBIT_A	5.203f*ASTRONOMIC_UNIT
#define SATURNE_ORBIT_A	9.54f*ASTRONOMIC_UNIT
#define URANUS_ORBIT_A	19.19f*ASTRONOMIC_UNIT
#define NEPTUNE_ORBIT_A	30.06f*ASTRONOMIC_UNIT
#define PLUTON_ORBIT_A	39.44f*ASTRONOMIC_UNIT

// Orbit Excentricity
#define MERCURE_ORBIT_E	0.206f
#define VENUS_ORBIT_E	0.007f
#define TERRE_ORBIT_E	0.017f
#define MARS_ORBIT_E	0.093f
#define JUPITER_ORBIT_E	0.048f
#define SATURNE_ORBIT_E	0.056f
#define URANUS_ORBIT_E	0.046f
#define NEPTUNE_ORBIT_E	0.010f
#define PLUTON_ORBIT_E	0.248f

// Periodes de revolution (s)
#define MERCURE_ORBIT_T	0.24f*SEC_PER_YEAR
#define VENUS_ORBIT_T	0.615f*SEC_PER_YEAR
#define TERRE_ORBIT_T	1.0f*SEC_PER_YEAR
#define MARS_ORBIT_T	1.88f*SEC_PER_YEAR
#define JUPITER_ORBIT_T	11.86f*SEC_PER_YEAR
#define SATURNE_ORBIT_T	29.46f*SEC_PER_YEAR
#define URANUS_ORBIT_T	84.04f*SEC_PER_YEAR
#define NEPTUNE_ORBIT_T	164.8f*SEC_PER_YEAR
#define PLUTON_ORBIT_T	247.7f*SEC_PER_YEAR

// Masses relatives a la Terre
#define	SOLEIL_RELATIVE_MASS	330000.0f
#define MERCURE_RELATIVE_MASS	0.056f
#define VENUS_RELATIVE_MASS		0.82f
#define TERRE_RELATIVE_MASS		1.0f
#define MARS_RELATIVE_MASS		0.11f
#define JUPITER_RELATIVE_MASS	318.0f
#define SATURN_RELATIVE_MASS	95.0f
#define URANUS_RELATIVE_MASS	15.0f
#define NEPTUNE_RELATIVE_MASS	17.0f
#define PLUTON_RELATIVE_MASS	0.002f


#endif
